-- detallado
SELECT FCC.TIDO as tipo,FCC.NUDO as numero,FCC.ENDO as proveedor,
       FCC.KOPRCT as codigo,FCC.NOKOPR as descripcion,
	   convert( nvarchar(10),FCC.FEERLI,103) as fechallegada,FCC.CAPRCO1 as cantidad
FROM MAEDDO AS FCC  (NOLOCK)
LEFT JOIN MAEDDO AS GRC (NOLOCK) ON FCC.IDMAEDDO=GRC.IDRST AND GRC.ARCHIRST='MAEDDO'
LEFT JOIN MAEDDO AS OCC (NOLOCK) ON FCC.IDRST=OCC.IDMAEDDO AND FCC.ARCHIRST='MAEDDO'
INNER JOIN MAEEN (NOLOCK) ON FCC.ENDO=MAEEN.KOEN AND FCC.SUENDO=MAEEN.SUEN
WHERE FCC.TIDO='FCC' 
	AND GRC.TIDO IS NULL 
	AND OCC.TIDO IS NOT NULL 
	AND ( MAEEN.PAEN <>'CHI' OR FCC.ENDO = '77072570EX' )
	AND FCC.FEEMLI>=dateadd(dd,-120,GETDATE())
ORDER BY FCC.FEERLI DESC
		
-- resumido por producto
SELECT FCC.KOPRCT as codigo, FCC.NOKOPR as descripcion, SUM(FCC.CAPRCO1) as cantidad 
FROM MAEDDO AS FCC  (NOLOCK)
LEFT JOIN MAEDDO AS GRC (NOLOCK) ON FCC.IDMAEDDO=GRC.IDRST AND GRC.ARCHIRST='MAEDDO'
LEFT JOIN MAEDDO AS OCC (NOLOCK) ON FCC.IDRST=OCC.IDMAEDDO AND FCC.ARCHIRST='MAEDDO'
INNER JOIN MAEEN (NOLOCK) ON FCC.ENDO=MAEEN.KOEN AND FCC.SUENDO=MAEEN.SUEN
WHERE FCC.TIDO='FCC' 
	AND GRC.TIDO IS NULL 
	AND OCC.TIDO IS NOT NULL 
	AND ( MAEEN.PAEN <>'CHI' OR FCC.ENDO = '77072570EX' )
	AND FCC.FEEMLI>=dateadd(dd,-120,GETDATE())
group by FCC.KOPRCT, FCC.NOKOPR
ORDER BY FCC.KOPRCT DESC
