WITH 
STOCK_RANDOM_701 AS (SELECT ST.KOPR, ST.STFI1
					 FROM MAEST AS ST WITH (NOLOCK)
                     WHERE ST.KOBO = 'CLM' ), 
STOCK_TRANS_ENTRADA AS (SELECT DO.KOPRCT, DO.CAPRCO1, DO.TIDO, DO.NUDO
                        FROM MAEDDO AS DO WITH (NOLOCK)
                        WHERE DO.TIDO IN ('GTI','GDI')   -- creo que debes cambiar el tipo de documento a unos de entrada GTI,GRI
						  AND DO.SUENDO = '1CM'
						  AND DO.FEEMLI > '20180131' 
						  AND DO.ESLIDO = '' ), 
STOCK_TRANS_SALIDA AS (SELECT KOPRCT, CAPRCO1, TIDO, NUDO
                       FROM MAEDDO AS D WITH (NOLOCK)
                       WHERE D.TIDO IN ('GTI','GDI')     
					     AND D.SUENDO <> '1CM' 
						 AND D.FEEMLI > '20180131' 
						 AND D.ESLIDO = '' ), 
DEVENGADO AS (SELECT KOPRCT, SUM(CAPRCO1) AS X1
              FROM MAEDDO AS O WITH (NOLOCK)
              WHERE O.TIDO IN ('FCV', 'BLV') 
			    AND O.BOSULIDO = '1CM' 
				AND O.FEEMLI > '20180131' 
				AND ESLIDO = ''
              GROUP BY KOPRCT, TIDO, NUDO) 
SELECT BO.KOBO AS BODEGA, PR.KOPR AS CODIGO, PR.NOKOPR AS DESCRIPCION,
       COALESCE (STTRAINT.TIDO,'SIN_DOC') AS DOC_PEND_INGRESO,
	   COALESCE (STTRAINT.NUDO,'SIN_DOC') AS NUM_DOC_PENDIENTE ,
	   COALESCE (STTRAINT.CAPRCO1, 0) AS CANT_PEND_INGRESO, 
	   COALESCE (STTRAOUT.TIDO,'SIN_DOC') AS DOC_SALIDA_WAYUP,
	   COALESCE (STTRAOUT.NUDO,'SIN_DOC') AS NUM_PEND_WAYUP,
	   COALESCE (STTRAOUT.CAPRCO1, 0) AS PEND_SALIDA_WAYUP, 
       COALESCE (NVV.X1, 0) AS DEVENGADO,
	   COALESCE (ST701.STFI1, 0) AS STOCK_RANDOM_701,
	   COALESCE((SELECT TOP 1 O.TIDO+' '+O.NUDO
				 FROM MAEDDO AS O WITH (NOLOCK)
			     WHERE O.TIDO IN ('FCV','BLV','GDV','GDP','GDI','GTI') 
			       AND O.BOSULIDO = 'CLM'
			       AND O.ESLIDO ='C'
			       AND O.KOPRCT=PR.KOPR	     
			     ORDER BY O.FEEMLI DESC),'') AS U_TIDONUDO,
	   COALESCE((SELECT TOP 1 O.CAPRCO1
				 FROM MAEDDO AS O WITH (NOLOCK)
			     WHERE O.TIDO IN ('FCV','BLV','GDV','GDP','GDI','GTI') 
			       AND O.BOSULIDO = 'CLM'
			       AND O.ESLIDO ='C'
			       AND O.KOPRCT=PR.KOPR	     
			     ORDER BY O.FEEMLI DESC),'') AS U_CANTIDAD
FROM MAEPR AS PR WITH (NOLOCK) 
INNER JOIN MAEST AS BO WITH (NOLOCK) ON BO.KOPR = PR.KOPR AND PR.TIPR = 'FPN' AND BO.KOBO = 'CLM' 
LEFT OUTER JOIN STOCK_RANDOM_701 AS ST701 ON ST701.KOPR = PR.KOPR 
LEFT OUTER JOIN STOCK_TRANS_ENTRADA AS STTRAINT ON STTRAINT.KOPRCT = PR.KOPR 
LEFT OUTER JOIN STOCK_TRANS_SALIDA AS STTRAOUT ON STTRAOUT.KOPRCT = PR.KOPR 
LEFT OUTER JOIN DEVENGADO AS NVV ON NVV.KOPRCT = PR.KOPR 
WHERE PR.KOPR ='AEANTENA00007'