ALTER TRIGGER [dbo].[TRIGGER_MAEEDO] ON [dbo].[MAEEDO] 
WITH ENCRYPTION

FOR UPDATE
AS 

DECLARE
	@EMPRESA	CHAR(2)
	,@IDMAEEDO	INT
	,@TIDO		char(3)
	,@NUDO		char(10)
	,@ENDO		char(13)
	,@ENDOFI	char(13)	
	,@ACTUENDO	char(13)
	,@NUDONODEFI INT
	,@NUDONODEFI_INI INT
	,@LUVTDO 	CHAR(8)
	,@TIGEDO	CHAR(1)
	,@FEEMDOACT datetime
	,@FEEMDO	datetime
	,@STATUS	INT
	,@SUDO		CHAR(3)
	,@BODESTI	CHAR(3)
	,@KOFUDO	CHAR(3)
	,@NUMERO	CHAR(10)
	,@NUMERO_ACT CHAR(10)
	,@ESDO		CHAR(1)
	,@SUBTIDO	CHAR(3)
	,@TIDOPA	CHAR(3)
	,@NUDOPA	CHAR(10)
	,@NUVEDO	INT
    ,@SUENDO	CHAR(10)
	,@DIPRVE	INT
	,@VANEDO	FLOAT
	,@VABRDO	FLOAT
	,@NUVECR	INT
	,@NUMEROGDI CHAR(10)
	,@KOLTPR	CHAR(8)
	,@PRODUCT_ERR CHAR(13)
	,@CAPRCO1 FLOAT
	,@STFI1 FLOAT
	,@STDV1 FLOAT
	,@SULIDO CHAR(3)
	,@BOSULIDO CHAR(3)
	,@VUELTA INT
	,@CAPRCO INT
	,@KOFUALIDO CHAR(3)
	
	SELECT
		@EMPRESA =  inserted.EMPRESA
		,@IDMAEEDO = inserted.IDMAEEDO
		,@TIDO	= inserted.TIDO
		,@NUDO = inserted.NUDO
 		,@ENDO = inserted.ENDO
		,@SUENDO = inserted.SUENDO
 		,@ENDOFI = inserted.ENDOFI
		,@LUVTDO = inserted.LUVTDO
 		,@NUDONODEFI = inserted.NUDONODEFI
 		,@TIGEDO = inserted.TIGEDO
 		,@SUDO = inserted.SUDO
		,@KOFUDO = inserted.KOFUDO
		,@ESDO = inserted.ESDO
		,@SUBTIDO = inserted.SUBTIDO
		,@CAPRCO = inserted.CAPRCO
		,@VANEDO = ROUND(inserted.VANEDO,0)
		,@VABRDO = ROUND(inserted.VABRDO,0)
	from 
		inserted

	SELECT 
 		@ACTUENDO = deleted.ENDO, @NUDONODEFI_INI = deleted.NUDONODEFI
	from 
		deleted


	IF @TIDO IN ('NVV') AND @VANEDO < 500000
		AND EXISTS (SELECT TOP 1 'A' FROM MAEDDO (NOLOCK) WHERE IDMAEEDO = @IDMAEEDO AND KOPRCT= 'DESCUENTO' ) 
	BEGIN
		PRINT 'NO PUEDE DAR DESCUENTO POR VENTAS MENORES A $ 500.000 MIL PESOS , NO PUEDE GRABAR.'
		ROLLBACK TRANSACTION
		PRINT 'NO PUEDE DAR DESCUENTO POR VENTAS MENORES A $ 500.000 MIL PESOS , NO PUEDE GRABAR.'

		RETURN
	END		

	IF @TIDO IN ('GDV','BLV','FCV','NVV') AND EXISTS (SELECT TOP 1 NUDO FROM MAEDDO (NOLOCK)
				WHERE IDMAEEDO = @IDMAEEDO AND KOLTPR = 'TABPP01C')
	BEGIN
	
		PRINT 'NO SE PUEDE VENDER CON LISTA DE COSTO'
		ROLLBACK TRANSACTION
		PRINT 'NO SE PUEDE VENDER CON LISTA DE COSTO'

		DELETE MAEEDO WHERE IDMAEEDO = @IDMAEEDO

		RETURN
	END

	IF @TIDO IN ('NVV') AND EXISTS (SELECT TOP 1 NUDO FROM MAEDDO (NOLOCK)
				INNER JOIN MAEPR (NOLOCK) ON MAEPR.KOPR = KOPRCT
				INNER JOIN TABPRE (NOLOCK) ON KOLT = SUBSTRING(KOLTPR,6,3) AND TABPRE.KOPR = KOPRCT 
				INNER JOIN TABCARAC (NOLOCK) ON KOTABLA = 'DSTOSXFAMI' AND SUBSTRING(KOCARAC,1,3) = KOFULIDO AND SUBSTRING(KOCARAC,5,4) = FMPR
				WHERE IDMAEEDO = @IDMAEEDO AND DTMA01UD = 0 AND PODTGLLI-0.1 > NOKOCARAC)
	BEGIN
	
		SELECT TOP 1 @PRODUCT_ERR = KOPRCT  FROM MAEDDO (NOLOCK)
		INNER JOIN MAEPR (NOLOCK) ON MAEPR.KOPR = KOPRCT
		INNER JOIN TABPRE (NOLOCK) ON KOLT = SUBSTRING(KOLTPR,6,3) AND TABPRE.KOPR = KOPRCT 
		INNER JOIN TABCARAC (NOLOCK) ON KOTABLA = 'DSTOSXFAMI' AND SUBSTRING(KOCARAC,1,3) = KOFULIDO AND SUBSTRING(KOCARAC,5,4) = FMPR
		WHERE IDMAEEDO = @IDMAEEDO AND DTMA01UD = 0 AND PODTGLLI-0.1 > NOKOCARAC
		
		PRINT 'NO SE PUEDE VENDER VER PORCENTAJE DE PRODUCTO ' + @PRODUCT_ERR 
		ROLLBACK TRANSACTION
		PRINT 'NO SE PUEDE VENDER VER PORCENTAJE DE PRODUCTO ' + @PRODUCT_ERR

		DELETE MAEEDO WHERE IDMAEEDO = @IDMAEEDO

		RETURN
	END

	IF @TIDO IN ('BLV','FCV') AND RTRIM(@ENDOFI) = 'CON' AND EXISTS ( SELECT TOP 1 'A' FROM MAEDDO (NOLOCK) 
			INNER JOIN MAEPR ON KOPR = KOPRCT WHERE IDMAEEDO = @IDMAEEDO)
	BEGIN
		UPDATE MAEST SET STFI1 = STFI1 + CAPRAD1, STFI2 = STFI2 + CAPRAD2, STDV1 = STDV1 + CAPRAD1, STDV2 = STDV2 + CAPRAD2
		FROM MAEST
		INNER JOIN MAEDDO ON KOPRCT = KOPR AND SULIDO = KOSU AND BOSULIDO = KOBO
		WHERE IDMAEEDO = @IDMAEEDO
		
		UPDATE MAEPR SET STFI1 = STFI1 + CAPRAD1, STFI2 = STFI2 + CAPRAD2, STDV1 = STDV1 + CAPRAD1, STDV2 = STDV2 + CAPRAD2
		FROM MAEPR
		INNER JOIN MAEDDO ON KOPRCT = KOPR
		WHERE IDMAEEDO = @IDMAEEDO
		
		UPDATE MAEPREM SET STFI1 = STFI1 + CAPRAD1, STFI2 = STFI2 + CAPRAD2, STDV1 = STDV1 + CAPRAD1, STDV2 = STDV2 + CAPRAD2
		FROM MAEPREM
		INNER JOIN MAEDDO ON KOPRCT = KOPR
		WHERE IDMAEEDO = @IDMAEEDO
		
		UPDATE MAEDDO SET  LINCONDESP = 0, ESLIDO = ' ', CAPRAD1 = 0, CAPRAD2 = 0
		WHERE IDMAEEDO = @IDMAEEDO
		
		UPDATE MAEEDO SET  ESDO = ' ', CAPRAD = 0
		WHERE IDMAEEDO = @IDMAEEDO
	END

	IF @TIDO IN ('GDV','BLV','FCV') AND NOT EXISTS (SELECT NUDO FROM CORREO_ENVIO_DOCTOS (NOLOCK)
				WHERE TIPO = @TIDO AND NUDO = @NUDO AND ENDO = @ENDO)
	BEGIN
		INSERT INTO CORREO_ENVIO_DOCTOS
		SELECT 	@TIDO, @NUDO, @ENDO, @SUBTIDO
	END

	IF @TIDO IN ('GDV','BLV','FCV','NVV','COV') AND NOT EXISTS (SELECT NUMERO FROM A_DOCTOS_PARA_REVISION (NOLOCK)
				WHERE TIPO = @TIDO AND NUMERO = @NUDO AND ENTIDAD = @ENDO)
	BEGIN
		INSERT INTO A_DOCTOS_PARA_REVISION
		SELECT 	@TIDO, @NUDO, @ENDO
	END

	IF @TIDO IN ('GDI','GRI') AND @SUBTIDO = 'AJU'
	BEGIN
		INSERT INTO CORREO_ENVIO_DOCTOS
		SELECT 	@TIDO, @NUDO, @ENDO, @SUBTIDO
	END

	IF @TIDO IN ('OCC') AND EXISTS (SELECT TOP 1 NUDO FROM MAEDDO (NOLOCK) WHERE IDMAEEDO = @IDMAEEDO)
	BEGIN
		INSERT INTO INFORMACION_EMPRESA_COMPRAS_Y_STOCK
		SELECT KOPRCT,NUDO,FEEMLI,STFI1
		FROM MAEDDO (NOLOCK)
		INNER JOIN MAEPR (NOLOCK) ON KOPR = KOPRCT	
	END
	
	IF @TIDO IN ('OCC','NVI','NVV','BLV') AND EXISTS ( SELECT TOP 1 BOSULIDO FROM MAEDDO (NOLOCK) 
					INNER JOIN TABCARAC (NOLOCK) ON KOTABLA = 'BODEGASWAY' AND KOCARAC = BOSULIDO
					WHERE IDMAEEDO = @IDMAEEDO )
	BEGIN

		IF @TIDO = 'BLV' AND EXISTS (SELECT TOP 1 'A' FROM MAEEDO (NOLOCK) 
			INNER JOIN MAEDDO (NOLOCK) ON MAEDDO.IDMAEEDO = MAEEDO.IDMAEEDO
			WHERE MAEEDO.IDMAEEDO = @IDMAEEDO AND IDRST = 0)					
		BEGIN

			INSERT INTO MAEEDO_WAYUP
			SELECT @IDMAEEDO

			UPDATE MAEST SET STFI1 = STFI1 + CAPRAD1, STFI2 = STFI2 + CAPRAD2, STDV1 = STDV1 + CAPRAD1, STDV2 = STDV2 + CAPRAD2
			FROM MAEST
			INNER JOIN MAEDDO ON KOPRCT = KOPR AND SULIDO = KOSU AND BOSULIDO = KOBO
			WHERE IDMAEEDO = @IDMAEEDO
		
			UPDATE MAEPR SET STFI1 = STFI1 + CAPRAD1, STFI2 = STFI2 + CAPRAD2, STDV1 = STDV1 + CAPRAD1, STDV2 = STDV2 + CAPRAD2
			FROM MAEPR
			INNER JOIN MAEDDO ON KOPRCT = KOPR
			WHERE IDMAEEDO = @IDMAEEDO
		
			UPDATE MAEPREM SET STFI1 = STFI1 + CAPRAD1, STFI2 = STFI2 + CAPRAD2, STDV1 = STDV1 + CAPRAD1, STDV2 = STDV2 + CAPRAD2
			FROM MAEPREM
			INNER JOIN MAEDDO ON KOPRCT = KOPR
			WHERE IDMAEEDO = @IDMAEEDO
		
			UPDATE MAEDDO SET  LINCONDESP = 0, ESLIDO = ' ', CAPRAD1 = 0, CAPRAD2 = 0
			WHERE IDMAEEDO = @IDMAEEDO
		
			UPDATE MAEEDO SET  ESDO = ' ', CAPRAD = 0
			WHERE IDMAEEDO = @IDMAEEDO

		END
		
		IF @TIDO IN ('OCC','NVI','NVV')
		BEGIN 
			INSERT INTO MAEEDO_WAYUP
			SELECT @IDMAEEDO
		END

	END

	IF @TIDO IN ('GDI','GTI') AND EXISTS ( SELECT TOP 1 BOSULIDO FROM  MAEEDO (NOLOCK)
					INNER JOIN MAEDDO (NOLOCK) ON MAEDDO.IDMAEEDO = MAEEDO.IDMAEEDO
					INNER JOIN TABCARAC (NOLOCK) ON KOTABLA = 'BODEGASWAY' AND KOCARAC = BODESTI
					WHERE MAEEDO.IDMAEEDO = @IDMAEEDO )
	BEGIN

		INSERT INTO MAEEDO_WAYUP
		SELECT @IDMAEEDO	

	END

RETURN







